# Simple workflow for deploying static content to GitHub Pages
name: Deploy `./build` static content to SFTP site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["simple-site"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: 3rd-party-sftp
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Dump version
        run: |
          node -v
          npm --version
          git --version

      - name: NPM Install
        run: npm ci --ignore-scripts

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build

      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }}
            local_path: './build'
            remote_path: '/'
            sftp_only: false
            password: ${{ secrets.FTP_PASSWORD }}